import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { HeaderIndex } from "@/components/layout/header";
import { Toaster } from "@/components/ui/sonner";
import { FloatingLiveChat } from "@/components/messaging/floating-live-chat";
import { FloatingThemeToggle } from "@/components/ui/floating-theme-toggle";
import { QueryProvider } from "@/components/providers/query-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: { template: "%s | taufaniafrinda", absolute: "taufaniafrinda" },
  // description: { template: "%s |", absolute: "taufaniafrinda" },
  description: "Taufania Frinda Personal Site",
  verification: {
    other: {
      "algolia-site-verification": "51B5D1F7089DA45A",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider
        attribute={"class"}
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <QueryProvider>
            <HeaderIndex />
            <main className="container mx-auto px-4 py-6 lg:px-24">
              {children}
            </main>
            <FloatingLiveChat />
            <FloatingThemeToggle />
            <Toaster />
          </QueryProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
